# Generated by Django 5.2.15 on 2026-06-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('image', models.ImageField(upload_to='certificate/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['-created_at'], 'verbose_name': 'Слайд портфолио', 'verbose_name_plural': 'Слайды портфолио'},
        ),
    ]
