# Generated by Django 5.2.15 on 2026-06-18 09:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_callbackrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackrequest',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=60, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
