# Generated by Django 5.2.15 on 2026-06-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_callbackrequest_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callbackrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка с сайта', 'verbose_name_plural': 'Заявки с сайта'},
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Комментарий клиента'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
