# Generated by Django 5.2.15 on 2026-06-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(upload_to='company/', verbose_name='Изображение компании'),
        ),
    ]
