# Generated by Django 5.2.15 on 2026-07-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_attribute_slug_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
