# Generated by Django 5.2.15 on 2026-07-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_attribute_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('category', 'name', 'slug')},
        ),
    ]
