# Generated by Django 5.2.15 on 2026-07-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_attribute_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
