# Generated by Django 5.2.15 on 2026-09-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_category_description_category_short_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position'], 'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
    ]
